name: planets
description: My new Flutter app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  go_router: ^14.8.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  path: ^1.9.0
  path_provider: ^2.1.5
  riverpod: ^2.6.1
  sembast: ^3.8.2
  sembast_web: ^2.4.0+4
  slang: ^4.6.0
  slang_flutter: ^4.6.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  slang_build_runner: ^4.6.0
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true

